mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

# from mysite.views import hello, current_datetime, hours_ahead, \
#                             current_datetime2, current_datetime3, \
#                             current_datetime4, hours_ahead2
from mysite import views
import books.views



urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^hello/$', views.hello),
    # url(r'^time/$', current_datetime),
    # url(r'^time/$', current_datetime2),
    # url(r'^time/$', current_datetime3),
    url(r'^time/$', views.current_datetime4),
    # url(r'^time/plus/(\d{1,2})/$', hours_ahead),
    url(r'^time/plus/(\d{1,2})/$', views.hours_ahead2),
    url(r'^books/$', books.views.book_list),

    # url(r'^search_form/$', books.views.search_form),
    # url(r'^search/$', books.views.search),

    # url(r'^search/$', books.views.search2),   # combine form and result

    url(r'^search/$', books.views.search3),   # display custom error messages
    # url(r'^contact/$', books.views.contact),  # a simple contact form example

    url(r'^contact/$', books.views.contact2),   # display errors on the form 
                                                # directly if validation fails
    url(r'^contact/thanks/$', books.views.contact_thankyou),
]

books/models.py
from django.db import models

# Create your models here.
class Publisher(models.Model):
	name = models.CharField(max_length=30)
	address = models.CharField(max_length=50)
	city = models.CharField(max_length=60)
	state_province = models.CharField(max_length=30)
	country = models.CharField(max_length=50)
	website = models.URLField()

	# Create a string representation of the Publisher object
	def __str__(self):
		return self.name

	class Meta:
		ordering = ['name']

		

class Author(models.Model):
	first_name = models.CharField(max_length=30)
	last_name = models.CharField(max_length=40)
	# email = models.EmailField()
	email = models.EmailField(blank=True)

	# Create a string representation of the Author object
	def __str__(self):
		return '{0} {1}'.format(self.last_name, self.first_name)



class Book(models.Model):
	title = models.CharField(max_length=100)

	# Unlike other fields, 'authors' is not a data column, it
	# represents a many-to-many relationship among books and 
	# authors: a books has one more authors, an author writes
	# one or many books.
	# 
	# Actually a joint table is created to handle the mapping
	# from books to authors.
	authors = models.ManyToManyField(Author)

	# Since a book has one and only one publisher, to express
	# this one-to-one relationship, use 'ForeignKey'.
	publisher = models.ForeignKey(Publisher)

	publication_date = models.DateField(blank=True, null=True)

	def __str__(self):
		return self.title

books/forms.py
# All forms class for the Book app goes here.
from django import forms



class ContactForm(forms.Form):
	"""
	Using Django forms.
	"""
	# maxlength defines a built in validation logic.
	subject = forms.CharField(max_length=20)

	# An EmailField has built in validation logic, which tells the 
	# client to include '@' and contains characters both in front of
	# and after the '@' symbol.
	email = forms.EmailField(required=False)

	# CharField is the type, but widget is the presentation logic,
	# which tells the browser to create a area specialized for large
	# amount of text input.
	message = forms.CharField(widget=forms.Textarea)



	def clean_message(self):
		"""
		The method to further validate and transform the 'message'
		field after the field has been validated by Django forms' built
		in validation logic.
		"""
		message = self.cleaned_data['message']

		# Make sure the message has at least 3 words. If not, then
		# raise a validation error.
		num_words = len(message.split())
		if num_words < 3:
			raise forms.ValidationError('There should be at least 3 words.')

		return message



	def clean_subject(self):
		"""
		For the 'subject' field. Here we just change the field value.
		"""
		return 'client subject: ' + self.cleaned_data['subject']

books/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, Http404
from .models import Book
from .forms import ContactForm
import logging

# Get an instance of a logger
logger = logging.getLogger('my apps')



# Create your views here.
def book_list(request):
	"""
	Use the shortcut render() function to do template rendering.
	"""
	return render(request, 'book_list.html',
					{'books':Book.objects.all()})



def search(request):
	# if the user has submitted a search form ('q in request.GET') and
	# the search query is non-empty (request.GET['q'] != '')
	if 'q' in request.GET and request.GET['q']:
		q = request.GET['q']
		books = Book.objects.filter(title__icontains=q)
		return render(request, 'search_result.html', {'books':books, 'query':q})
	else:
		return render(request, 'search_form.html', {'error': True})



def search_form(request):
	# display the search form
	return render(request, 'search_form.html', {'error': False})




def search2(request):
	# An improved search view, where it can:
	# 1. Serve the search form if parameter 'q' is not there,
	# 2. Serve the search form with an error if 'q' is empty,
	# 3. Serve the search result
	error = False
	if 'q' in request.GET:
		q = request.GET['q']
		if q != '':
			books = Book.objects.filter(title__icontains=q)
			return render(request, 'search_result.html', {'books':books, 'query':q})
		else:
			error = True

	return render(request, 'search_form.html', {'error': error})



def search3(request):
	# An improved search view, where it can:
	# 1. Serve the search form if parameter 'q' is not there,
	# 2. Serve the search form with custom error messages if 'q' is empty,
	# 3. Serve the search result
	logger.info('search3(): enter')
	errors = []	# instead of using a Boolean, using a message list
	if 'q' in request.GET:
		q = request.GET['q']
		if q == '':
			logger.error('search3(): query is empty.')
			errors.append('Search query cannot be empty.')
		elif len(q) > 20:
			logger.error('search3(): query \"{0}\" is too long.'.format(q))
			errors.append('Search query must be less than 20 characters')
		else:
			logger.debug('search3(): query={0}'.format(q))
			books = Book.objects.filter(title__icontains=q)
			return render(request, 'search_result.html', {'books':books, 'query':q})

	return render(request, 'search_form3.html', {'errors': errors})



def contact(request):
	if request.method == 'GET':
		# an empty form
		# form = ContactForm()

		# a form with some pre-populated values to the fields
		form = ContactForm(
				initial={'subject':'What a lovely site!'}
			)
		# return render(request, 'contact_form.html', {'form':form})
		return render(request, 'contact_form2.html', {'form':form})
		
	elif request.method == 'POST':
		form = ContactForm(request.POST)
		if form.is_valid():
			# do some processing here
			# cd = form.cleaned_data
			# send_mail(cd ...)
			return HttpResponseRedirect('/contact/thanks/')
		else:
			return HttpResponse('<html><body><h1>Ooops, something is wrong</h1></body></html>')
	else:
		raise Http404()



def contact2(request):
	logger.info('contact2(): enter')
	if request.method == 'GET':
		logger.debug('contact2(): handling GET')
		# an empty form
		# form = ContactForm()

		# a form with some pre-populated values to the fields
		form = ContactForm(
				initial={'subject':'What a lovely site!'}
			)
		return render(request, 'contact_form2.html', {'form':form})
		
	elif request.method == 'POST':
		logger.debug('contact2(): handling POST')
		form = ContactForm(request.POST)
		if form.is_valid():
			logger.debug('contact2() form valid: {0}, {1}, {2}'.format(
				form.cleaned_data['subject'], form.cleaned_data['email'], form.cleaned_data['message']))
			# do some processing here
			# cd = form.cleaned_data
			# send_mail(cd ...)
			return HttpResponseRedirect('/contact/thanks/')
		else:
			logger.warning('contact2(): form has invalid data')
			return render(request, 'contact_form2.html', {'form':form})
	
	else:
		logger.error('contact2(): invalid method called: {0}'.format(request.method))
		raise Http404()



def contact_thankyou(request):
	return render(request, 'contact_thankyou.html', {})

books/templates/book_list.html
<!-- This is a template page based on Django Template Language (DTL) -->
{% extends 'base.html' %}

<!-- Override block named 'title' in parent template -->
{% block title %}Book List{% endblock %}

{% block heading %}
<h1>The books site</h1>
{% endblock %}

<!-- Override block named 'content' in parent template -->
{% block content %}
<p>Found {{ books|length }} book{{ books|pluralize }}</p>
<ul>
	{% for book in books %}
	<li>{{ book.title }}, {{ book.publisher }}</li>
	{% endfor %}
</ul>
{% endblock %}

{% block footer %}
<hr>
<p>The book list for now</p>
{% endblock %}

books/templates/contact_form.html
<!-- This is a template page based on Django Template Language (DTL) -->
{% extends 'base.html' %}

<!-- Override block named 'title' in parent template -->
{% block title %}Contact Form{% endblock %}

{% block heading %}
<h1>Contact Us</h1>
{% endblock %}

<!-- Override block named 'content' in parent template -->
{% block content %}
	{% if form.errors %}
		<p style="color: red;">Error{{ form.errors|pluralize }} occurred.</p>
	{% endif %}

	<form action="" method="POST">
		<table>{{ form.as_table }}</table>
		{% csrf_token %}
		<input type="submit" value="submit">
	</form>
{% endblock %}

books/templates/contact_form2.html
<!-- This is a template page based on Django Template Language (DTL) -->
{% extends 'base.html' %}

<!-- Override block named 'title' in parent template -->
{% block title %}Contact Form{% endblock %}

{% block heading %}
<h1>Contact Us</h1>
{% endblock %}

<!-- Override block named 'content' in parent template -->
{% block content %}
	{% if form.errors %}
		<p style="color: red;">Error{{ form.errors|pluralize }} occurred.</p>
	{% endif %}

	<form action="" method="POST">
		<table>
			<div>
				<!-- below is the same as an empty string if no errors, otherwise <ul class="errorlist"><li>xxxx</li></ul> -->
				<!-- The css style is in base.html -->
				{{ form.subject.errors }}

				<!-- here the id field "id_subject" comes from django's default handling. In a shell environment, when you do print(form.as_table), you will see the id for field "subject" is "id_subject", etc. -->
				<label for="id_subject">Subject:</label>

				<!-- below is the same as <input id="id_subject" name="subject" type="email" /> -->
				{{ form.subject }}
			</div><br>

			<div>
				{{ form.email.errors }}
				<label for="id_email">You email address:</label>
				{{ form.email }}
			</div><br>

			<div>
				{{ form.message.errors }}
				<label for="id_message">Message:</label>
				{{ form.message }}
			</div><br>

		</table>

		<!-- Must be included, otherwise 403 forbidden -->
		{% csrf_token %}
		<input type="submit" value="submit">
	</form>
{% endblock %}

books/templates/contact_thankyou.html
<!-- This is a template page based on Django Template Language (DTL) -->
{% extends 'base.html' %}

<!-- Override block named 'title' in parent template -->
{% block title %}Thank you.{% endblock %}

{% block heading %}
<h1>Thank you for submitting the form.</h1>
{% endblock %}

books/templates/search_form.html
<!-- This is a template page based on Django Template Language (DTL) -->
{% extends 'base.html' %}

<!-- Override block named 'title' in parent template -->
{% block title %}Search form{% endblock %}

{% block heading %}
<h1>The Books Site</h1>
{% endblock %}

<!-- Override block named 'content' in parent template -->
{% block content %}
{% if error %}
<p>The search query cannot be empty.</p>
{% endif %}
<form action="/search", method="GET">
	<input type="text", name="q">
	<input type="submit", name="Search">
</form>
{% endblock %}

books/templates/search_form3.html
<!-- To be used with search3 view function -->
<!-- This is a template page based on Django Template Language (DTL) -->
{% extends 'base.html' %}

<!-- Override block named 'title' in parent template -->
{% block title %}Search form{% endblock %}

{% block heading %}
	<h1>The Books Site</h1>
{% endblock %}

<!-- Override block named 'content' in parent template -->
{% block content %}

	{% if errors %}
		<ul>
			{% for error in errors %}
			<li>{{ error }}</li>
			{% endfor %}
		</ul>
	{% endif %}
	<form action="/search", method="GET">
		<input type="text", name="q">
		<input type="submit", name="Search">
	</form>
{% endblock %}

books/templates/search_result.html
<!-- This is a template page based on Django Template Language (DTL) -->
{% extends 'base.html' %}

<!-- Override block named 'title' in parent template -->
{% block title %}Book List{% endblock %}

{% block heading %}
	<h1>The Books Site</h1>
{% endblock %}

<!-- Override block named 'content' in parent template -->
{% block content %}
	<p>You searched for: <strong>{{ query }}</strong></p>

	{% if books %}
		<p>Found {{ books|length }} book{{ books|pluralize }}</p>
		<ul>
			{% for book in books %}
			<li>{{ book.title }}, {{ book.publisher }}</li>
			{% endfor %}
		</ul>
	{% else %}
		<p>No books matched your search criteria</p>
	{% endif %}
{% endblock %}

{% block footer %}
<hr>
<p>The book list for now</p>
{% endblock %}